# Generated by Django 4.2.6 on 2023-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_bike_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='bike',
            name='size',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(null=True, upload_to='images/bikes'),
        ),
    ]
