# Generated by Django 4.2.6 on 2023-10-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_bike_color_bike_size_alter_bike_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('size', models.PositiveSmallIntegerField(default=50)),
                ('brakes', models.CharField(choices=[('DM', 'Disc Mechanical'), ('DH', 'Disc Hydraulic'), ('DP', 'Dual-Pivot'), ('VB', 'MTB V-Brake'), ('CN', 'Cantilever')], default='DH', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='bike',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='size',
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='images/bikes'),
            preserve_default=False,
        ),
    ]
