# Generated by Django 4.2.6 on 2023-10-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_bikeoptions_remove_bike_color_remove_bike_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name': 'Bike', 'verbose_name_plural': 'Bikes'},
        ),
        migrations.AlterModelOptions(
            name='bikeoptions',
            options={'verbose_name': 'BikeOption', 'verbose_name_plural': 'BikeOptions'},
        ),
        migrations.AddField(
            model_name='bikeoptions',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental.bike'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikeoptions',
            name='groupset',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
