# Generated by Django 4.2.6 on 2023-10-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_bikecategory_rename_bike_bikeoptions_bike_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='bikeoptions',
            old_name='bike_id',
            new_name='bike',
        ),
    ]
