# Generated by Django 4.2.6 on 2023-10-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_rename_category_id_bike_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikecategory',
            name='published',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1),
        ),
    ]
