# Generated by Django 4.2.6 on 2023-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_news_alter_bike_image_alter_bike_image_rotated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='images/news'),
        ),
    ]
